#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated: 11/10/2021(m/d/y) 03:42:58 utc
r_mods = {
	"Abyss Jewel": {
		"scourge_implicit": [
			""
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Accuracy Rating with Axes",
			"#% increased Accuracy Rating with Bows",
			"#% increased Accuracy Rating with Claws",
			"#% increased Accuracy Rating with Daggers",
			"#% increased Accuracy Rating with Maces or Sceptres",
			"#% increased Accuracy Rating with Staves",
			"#% increased Accuracy Rating with Swords",
			"#% increased Accuracy Rating with Wands",
			"#% increased Attack Speed",
			"#% increased Attack Speed with Axes",
			"#% increased Attack Speed with Bows",
			"#% increased Attack Speed with Claws",
			"#% increased Attack Speed with Daggers",
			"#% increased Attack Speed with Maces or Sceptres",
			"#% increased Attack Speed with Staves",
			"#% increased Attack Speed with Swords",
			"#% increased Attack Speed with Wands",
			"#% increased Attack and Cast Speed",
			"#% increased Cast Speed",
			"#% increased Cast Speed while Dual Wielding",
			"#% increased Cast Speed while holding a Shield",
			"#% increased Cast Speed while wielding a Staff",
			"#% increased Chaos Damage with Attack Skills",
			"#% increased Chaos Damage with Spell Skills",
			"#% increased Cold Damage",
			"#% increased Cold Damage with Attack Skills",
			"#% increased Cold Damage with Spell Skills",
			"#% increased Critical Strike Chance for Spells while Dual Wielding",
			"#% increased Critical Strike Chance for Spells while holding a Shield",
			"#% increased Critical Strike Chance for Spells while wielding a Staff",
			"#% increased Damage",
			"#% increased Damage over Time",
			"#% increased Damage with Ailments",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Fire Damage with Attack Skills",
			"#% increased Fire Damage with Spell Skills",
			"#% increased Global Critical Strike Chance",
			"#% increased Lightning Damage",
			"#% increased Lightning Damage with Attack Skills",
			"#% increased Lightning Damage with Spell Skills",
			"#% increased Minion Accuracy Rating",
			"#% increased Physical Damage with Attack Skills",
			"#% increased Physical Damage with Axes",
			"#% increased Physical Damage with Bows",
			"#% increased Physical Damage with Claws",
			"#% increased Physical Damage with Daggers",
			"#% increased Physical Damage with Maces or Sceptres",
			"#% increased Physical Damage with Spell Skills",
			"#% increased Physical Damage with Staves",
			"#% increased Physical Damage with Swords",
			"#% increased Physical Damage with Wands",
			"#% increased Spell Damage while Dual Wielding",
			"#% increased Spell Damage while holding a Shield",
			"#% increased Spell Damage while wielding a Staff",
			"#% to Critical Strike Multiplier for Spells while Dual Wielding",
			"#% to Critical Strike Multiplier for Spells while holding a Shield",
			"#% to Critical Strike Multiplier for Spells while wielding a Staff",
			"#% to Critical Strike Multiplier with Axes",
			"#% to Critical Strike Multiplier with Bows",
			"#% to Critical Strike Multiplier with Claws",
			"#% to Critical Strike Multiplier with Daggers",
			"#% to Critical Strike Multiplier with Maces or Sceptres",
			"#% to Critical Strike Multiplier with Staves",
			"#% to Critical Strike Multiplier with Swords",
			"#% to Critical Strike Multiplier with Wands",
			"#% to Global Critical Strike Multiplier",
			"Minions deal #% increased Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed"
		],
		"corrupt_implicit": [
			"#% increased Damage",
			"#% increased Global Critical Strike Chance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Minions deal #% increased Damage",
			"Overwhelm #% Physical Damage Reduction"
		],
		"implicit": [
			""
		],
		"explicit": [
			"# to # Added Chaos Damage with Bow Attacks",
			"# to # Added Chaos Damage with Claw Attacks",
			"# to # Added Chaos Damage with Dagger Attacks",
			"# to # Added Cold Damage with Axe Attacks",
			"# to # Added Cold Damage with Bow Attacks",
			"# to # Added Cold Damage with Claw Attacks",
			"# to # Added Cold Damage with Dagger Attacks",
			"# to # Added Cold Damage with Mace or Sceptre Attacks",
			"# to # Added Cold Damage with Staff Attacks",
			"# to # Added Cold Damage with Sword Attacks",
			"# to # Added Cold Damage with Wand Attacks",
			"# to # Added Fire Damage with Axe Attacks",
			"# to # Added Fire Damage with Bow Attacks",
			"# to # Added Fire Damage with Claw Attacks",
			"# to # Added Fire Damage with Dagger Attacks",
			"# to # Added Fire Damage with Mace or Sceptre Attacks",
			"# to # Added Fire Damage with Staff Attacks",
			"# to # Added Fire Damage with Sword Attacks",
			"# to # Added Fire Damage with Wand Attacks",
			"# to # Added Lightning Damage with Axe Attacks",
			"# to # Added Lightning Damage with Bow Attacks",
			"# to # Added Lightning Damage with Claw Attacks",
			"# to # Added Lightning Damage with Dagger Attacks",
			"# to # Added Lightning Damage with Mace or Sceptre Attacks",
			"# to # Added Lightning Damage with Staff Attacks",
			"# to # Added Lightning Damage with Sword Attacks",
			"# to # Added Lightning Damage with Wand Attacks",
			"# to # Added Physical Damage with Axe Attacks",
			"# to # Added Physical Damage with Bow Attacks",
			"# to # Added Physical Damage with Claw Attacks",
			"# to # Added Physical Damage with Dagger Attacks",
			"# to # Added Physical Damage with Mace or Sceptre Attacks",
			"# to # Added Physical Damage with Staff Attacks",
			"# to # Added Physical Damage with Sword Attacks",
			"# to # Added Physical Damage with Wand Attacks",
			"# to # Added Spell Chaos Damage while Dual Wielding",
			"# to # Added Spell Chaos Damage while holding a Shield",
			"# to # Added Spell Chaos Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Cold Damage while Dual Wielding",
			"# to # Added Spell Cold Damage while holding a Shield",
			"# to # Added Spell Cold Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Fire Damage while Dual Wielding",
			"# to # Added Spell Fire Damage while holding a Shield",
			"# to # Added Spell Fire Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Lightning Damage while Dual Wielding",
			"# to # Added Spell Lightning Damage while holding a Shield",
			"# to # Added Spell Lightning Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Physical Damage while Dual Wielding",
			"# to # Added Spell Physical Damage while holding a Shield",
			"# to # Added Spell Physical Damage while wielding a Two Handed Weapon",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack Speed if you've dealt a Critical Strike Recently",
			"#% increased Cast Speed",
			"#% increased Cast Speed if you've dealt a Critical Strike Recently",
			"#% increased Critical Strike Chance if you haven't dealt a Critical Strike Recently",
			"#% increased Damage if you've Killed Recently",
			"#% increased Damage over Time while Dual Wielding",
			"#% increased Damage over Time while holding a Shield",
			"#% increased Damage over Time while wielding a Two Handed Weapon",
			"#% increased Global Critical Strike Chance",
			"#% to Critical Strike Multiplier if you've Killed Recently",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage to Attacks",
			"Adds # to # Chaos Damage to Spells",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage to Attacks",
			"Adds # to # Physical Damage to Spells",
			"Damage Penetrates #% Elemental Resistance if you haven't Killed Recently",
			"Enemies Maimed by you take #% increased Damage Over Time",
			"Gain #% of Physical Damage as Extra Fire Damage if you've dealt a Critical Strike Recently",
			"Minions deal # to # additional Chaos Damage",
			"Minions deal # to # additional Cold Damage",
			"Minions deal # to # additional Fire Damage",
			"Minions deal # to # additional Lightning Damage",
			"Minions deal # to # additional Physical Damage",
			"Minions deal #% increased Damage if you've used a Minion Skill Recently",
			"Minions have # to Accuracy Rating",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Attack and Cast Speed if you or your Minions have Killed Recently",
			"Minions have #% increased Cast Speed"
		],
	},
	"All Jewel": {
		"scourge_implicit": [
			""
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Accuracy Rating with Axes",
			"#% increased Accuracy Rating with Bows",
			"#% increased Accuracy Rating with Claws",
			"#% increased Accuracy Rating with Daggers",
			"#% increased Accuracy Rating with Maces or Sceptres",
			"#% increased Accuracy Rating with Staves",
			"#% increased Accuracy Rating with Swords",
			"#% increased Accuracy Rating with Wands",
			"#% increased Attack Speed",
			"#% increased Attack Speed with Axes",
			"#% increased Attack Speed with Bows",
			"#% increased Attack Speed with Claws",
			"#% increased Attack Speed with Daggers",
			"#% increased Attack Speed with Maces or Sceptres",
			"#% increased Attack Speed with Staves",
			"#% increased Attack Speed with Swords",
			"#% increased Attack Speed with Wands",
			"#% increased Attack and Cast Speed",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed while Dual Wielding",
			"#% increased Cast Speed while holding a Shield",
			"#% increased Cast Speed while wielding a Staff",
			"#% increased Chaos Damage",
			"#% increased Chaos Damage with Attack Skills",
			"#% increased Chaos Damage with Spell Skills",
			"#% increased Cold Damage",
			"#% increased Cold Damage with Attack Skills",
			"#% increased Cold Damage with Spell Skills",
			"#% increased Critical Strike Chance for Spells while Dual Wielding",
			"#% increased Critical Strike Chance for Spells while holding a Shield",
			"#% increased Critical Strike Chance for Spells while wielding a Staff",
			"#% increased Damage",
			"#% increased Damage over Time",
			"#% increased Damage with Ailments",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Fire Damage with Attack Skills",
			"#% increased Fire Damage with Spell Skills",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Lightning Damage with Attack Skills",
			"#% increased Lightning Damage with Spell Skills",
			"#% increased Melee Damage",
			"#% increased Minion Accuracy Rating",
			"#% increased Physical Damage with Attack Skills",
			"#% increased Physical Damage with Axes",
			"#% increased Physical Damage with Bows",
			"#% increased Physical Damage with Claws",
			"#% increased Physical Damage with Daggers",
			"#% increased Physical Damage with Maces or Sceptres",
			"#% increased Physical Damage with Spell Skills",
			"#% increased Physical Damage with Staves",
			"#% increased Physical Damage with Swords",
			"#% increased Physical Damage with Wands",
			"#% increased Spell Damage",
			"#% increased Spell Damage while Dual Wielding",
			"#% increased Spell Damage while holding a Shield",
			"#% increased Spell Damage while wielding a Staff",
			"#% reduced Mana Cost of Skills",
			"#% to Critical Strike Multiplier for Spells while Dual Wielding",
			"#% to Critical Strike Multiplier for Spells while holding a Shield",
			"#% to Critical Strike Multiplier for Spells while wielding a Staff",
			"#% to Critical Strike Multiplier with Axes",
			"#% to Critical Strike Multiplier with Bows",
			"#% to Critical Strike Multiplier with Claws",
			"#% to Critical Strike Multiplier with Daggers",
			"#% to Critical Strike Multiplier with Maces or Sceptres",
			"#% to Critical Strike Multiplier with Staves",
			"#% to Critical Strike Multiplier with Swords",
			"#% to Critical Strike Multiplier with Wands",
			"#% to Global Critical Strike Multiplier",
			"Minions deal #% increased Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed"
		],
		"corrupt_implicit": [
			"#% increased Damage",
			"#% increased Global Critical Strike Chance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Minions deal #% increased Damage",
			"Overwhelm #% Physical Damage Reduction"
		],
		"implicit": [
			""
		],
		"explicit": [
			"# to # Added Chaos Damage with Bow Attacks",
			"# to # Added Chaos Damage with Claw Attacks",
			"# to # Added Chaos Damage with Dagger Attacks",
			"# to # Added Cold Damage with Axe Attacks",
			"# to # Added Cold Damage with Bow Attacks",
			"# to # Added Cold Damage with Claw Attacks",
			"# to # Added Cold Damage with Dagger Attacks",
			"# to # Added Cold Damage with Mace or Sceptre Attacks",
			"# to # Added Cold Damage with Staff Attacks",
			"# to # Added Cold Damage with Sword Attacks",
			"# to # Added Cold Damage with Wand Attacks",
			"# to # Added Fire Damage with Axe Attacks",
			"# to # Added Fire Damage with Bow Attacks",
			"# to # Added Fire Damage with Claw Attacks",
			"# to # Added Fire Damage with Dagger Attacks",
			"# to # Added Fire Damage with Mace or Sceptre Attacks",
			"# to # Added Fire Damage with Staff Attacks",
			"# to # Added Fire Damage with Sword Attacks",
			"# to # Added Fire Damage with Wand Attacks",
			"# to # Added Lightning Damage with Axe Attacks",
			"# to # Added Lightning Damage with Bow Attacks",
			"# to # Added Lightning Damage with Claw Attacks",
			"# to # Added Lightning Damage with Dagger Attacks",
			"# to # Added Lightning Damage with Mace or Sceptre Attacks",
			"# to # Added Lightning Damage with Staff Attacks",
			"# to # Added Lightning Damage with Sword Attacks",
			"# to # Added Lightning Damage with Wand Attacks",
			"# to # Added Physical Damage with Axe Attacks",
			"# to # Added Physical Damage with Bow Attacks",
			"# to # Added Physical Damage with Claw Attacks",
			"# to # Added Physical Damage with Dagger Attacks",
			"# to # Added Physical Damage with Mace or Sceptre Attacks",
			"# to # Added Physical Damage with Staff Attacks",
			"# to # Added Physical Damage with Sword Attacks",
			"# to # Added Physical Damage with Wand Attacks",
			"# to # Added Spell Chaos Damage while Dual Wielding",
			"# to # Added Spell Chaos Damage while holding a Shield",
			"# to # Added Spell Chaos Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Cold Damage while Dual Wielding",
			"# to # Added Spell Cold Damage while holding a Shield",
			"# to # Added Spell Cold Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Fire Damage while Dual Wielding",
			"# to # Added Spell Fire Damage while holding a Shield",
			"# to # Added Spell Fire Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Lightning Damage while Dual Wielding",
			"# to # Added Spell Lightning Damage while holding a Shield",
			"# to # Added Spell Lightning Damage while wielding a Two Handed Weapon",
			"# to # Added Spell Physical Damage while Dual Wielding",
			"# to # Added Spell Physical Damage while holding a Shield",
			"# to # Added Spell Physical Damage while wielding a Two Handed Weapon",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Area Damage",
			"#% increased Attack Critical Strike Chance while Dual Wielding",
			"#% increased Attack Damage while Dual Wielding",
			"#% increased Attack Damage while holding a Shield",
			"#% increased Attack Speed",
			"#% increased Attack Speed if you've dealt a Critical Strike Recently",
			"#% increased Attack Speed while Dual Wielding",
			"#% increased Attack Speed while holding a Shield",
			"#% increased Attack Speed with Axes",
			"#% increased Attack Speed with Bows",
			"#% increased Attack Speed with Claws",
			"#% increased Attack Speed with Daggers",
			"#% increased Attack Speed with Maces or Sceptres",
			"#% increased Attack Speed with One Handed Melee Weapons",
			"#% increased Attack Speed with Staves",
			"#% increased Attack Speed with Swords",
			"#% increased Attack Speed with Two Handed Melee Weapons",
			"#% increased Attack Speed with Wands",
			"#% increased Attack and Cast Speed",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed if you've dealt a Critical Strike Recently",
			"#% increased Cast Speed while Dual Wielding",
			"#% increased Cast Speed while holding a Shield",
			"#% increased Cast Speed while wielding a Staff",
			"#% increased Cast Speed with Cold Skills",
			"#% increased Cast Speed with Fire Skills",
			"#% increased Cast Speed with Lightning Skills",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Critical Strike Chance if you haven't dealt a Critical Strike Recently",
			"#% increased Critical Strike Chance with Cold Skills",
			"#% increased Critical Strike Chance with Elemental Skills",
			"#% increased Critical Strike Chance with Fire Skills",
			"#% increased Critical Strike Chance with Lightning Skills",
			"#% increased Critical Strike Chance with One Handed Melee Weapons",
			"#% increased Critical Strike Chance with Two Handed Melee Weapons",
			"#% increased Damage",
			"#% increased Damage if you've Killed Recently",
			"#% increased Damage over Time",
			"#% increased Damage over Time while Dual Wielding",
			"#% increased Damage over Time while holding a Shield",
			"#% increased Damage over Time while wielding a Two Handed Weapon",
			"#% increased Damage with Axes",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Bows",
			"#% increased Damage with Claws",
			"#% increased Damage with Daggers",
			"#% increased Damage with Maces or Sceptres",
			"#% increased Damage with One Handed Weapons",
			"#% increased Damage with Poison",
			"#% increased Damage with Staves",
			"#% increased Damage with Swords",
			"#% increased Damage with Two Handed Weapons",
			"#% increased Damage with Wands",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Melee Critical Strike Chance",
			"#% increased Melee Damage",
			"#% increased Mine Damage",
			"#% increased Minion Accuracy Rating",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Spell Damage while Dual Wielding",
			"#% increased Spell Damage while holding a Shield",
			"#% increased Spell Damage while wielding a Staff",
			"#% increased Totem Damage",
			"#% increased Totem Life",
			"#% increased Trap Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Critical Strike Multiplier for Spells",
			"#% to Critical Strike Multiplier if you've Killed Recently",
			"#% to Critical Strike Multiplier while Dual Wielding",
			"#% to Critical Strike Multiplier with Cold Skills",
			"#% to Critical Strike Multiplier with Elemental Skills",
			"#% to Critical Strike Multiplier with Fire Skills",
			"#% to Critical Strike Multiplier with Lightning Skills",
			"#% to Critical Strike Multiplier with One Handed Melee Weapons",
			"#% to Critical Strike Multiplier with Two Handed Melee Weapons",
			"#% to Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"#% to Melee Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage to Attacks",
			"Adds # to # Chaos Damage to Spells",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage to Attacks",
			"Adds # to # Physical Damage to Spells",
			"Damage Penetrates #% Elemental Resistance if you haven't Killed Recently",
			"Damaging Ailments deal damage #% faster",
			"Enemies Maimed by you take #% increased Damage Over Time",
			"Gain #% of Physical Damage as Extra Fire Damage if you've dealt a Critical Strike Recently",
			"Minions deal # to # additional Chaos Damage",
			"Minions deal # to # additional Cold Damage",
			"Minions deal # to # additional Fire Damage",
			"Minions deal # to # additional Lightning Damage",
			"Minions deal # to # additional Physical Damage",
			"Minions deal #% increased Damage",
			"Minions deal #% increased Damage if you've used a Minion Skill Recently",
			"Minions have # to Accuracy Rating",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Attack and Cast Speed if you or your Minions have Killed Recently",
			"Minions have #% increased Cast Speed"
		],
	},
	"Amulet": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Area Damage",
			"#% increased Cast Speed",
			"#% increased Dexterity",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Global Critical Strike Chance",
			"#% increased Intelligence",
			"#% increased Strength",
			"#% increased Totem Life",
			"#% to Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"Damage Penetrates #% Chaos Resistance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance"
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"#% increased Area Damage",
			"#% increased Attack and Cast Speed",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage per 15 Dexterity",
			"#% increased Damage per 15 Intelligence",
			"#% increased Damage per 15 Strength",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage while Leeching",
			"#% increased Damage with Ailments",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Melee Damage",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Global Critical Strike Multiplier",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Grace has #% increased Aura Effect",
			"Minions deal #% increased Damage"
		],
		"corrupt_implicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"#% increased Attack Damage",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Attributes",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage",
			"#% increased Dexterity",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% to Global Critical Strike Multiplier",
			"Anger has #% increased Aura Effect",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Gain #% of Physical Damage as Extra Damage of a random Element",
			"Grace has #% increased Aura Effect",
			"Hatred has #% increased Aura Effect",
			"Malevolence has #% increased Aura Effect",
			"Pride has #% increased Aura Effect",
			"Wrath has #% increased Aura Effect",
			"Zealotry has #% increased Aura Effect"
		],
		"implicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes"
		],
		"explicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Level of all Chaos Skill Gems",
			"# to Level of all Cold Skill Gems",
			"# to Level of all Dexterity Skill Gems",
			"# to Level of all Fire Skill Gems",
			"# to Level of all Intelligence Skill Gems",
			"# to Level of all Lightning Skill Gems",
			"# to Level of all Physical Skill Gems",
			"# to Level of all Strength Skill Gems",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% chance to deal Double Damage if you have Stunned an Enemy Recently",
			"#% increased Area Damage",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Attributes",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage per 15 Dexterity",
			"#% increased Damage per 15 Intelligence",
			"#% increased Damage per 15 Strength",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage while Leeching",
			"#% increased Dexterity",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Melee Damage",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Physical Damage to Attacks",
			"Adds # to # Physical Damage to Spells",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Gain #% of Non-Chaos Damage as extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage",
			"Minions deal #% increased Damage"
		],
	},
	"Base Jewel": {
		"scourge_implicit": [
			""
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack Speed with Axes",
			"#% increased Attack Speed with Bows",
			"#% increased Attack Speed with Claws",
			"#% increased Attack Speed with Daggers",
			"#% increased Attack Speed with Maces or Sceptres",
			"#% increased Attack Speed with Staves",
			"#% increased Attack Speed with Swords",
			"#% increased Attack Speed with Wands",
			"#% increased Attack and Cast Speed",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed while Dual Wielding",
			"#% increased Cast Speed while holding a Shield",
			"#% increased Cast Speed while wielding a Staff",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage",
			"#% increased Damage over Time",
			"#% increased Damage with Ailments",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Melee Damage",
			"#% increased Physical Damage with Axes",
			"#% increased Physical Damage with Bows",
			"#% increased Physical Damage with Claws",
			"#% increased Physical Damage with Daggers",
			"#% increased Physical Damage with Maces or Sceptres",
			"#% increased Physical Damage with Staves",
			"#% increased Physical Damage with Swords",
			"#% increased Physical Damage with Wands",
			"#% increased Spell Damage",
			"#% increased Spell Damage while Dual Wielding",
			"#% increased Spell Damage while holding a Shield",
			"#% increased Spell Damage while wielding a Staff",
			"#% reduced Mana Cost of Skills",
			"#% to Global Critical Strike Multiplier",
			"Minions deal #% increased Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed"
		],
		"corrupt_implicit": [
			"#% increased Damage",
			"#% increased Global Critical Strike Chance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Minions deal #% increased Damage",
			"Overwhelm #% Physical Damage Reduction"
		],
		"implicit": [
			""
		],
		"explicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"#% increased Area Damage",
			"#% increased Attack Critical Strike Chance while Dual Wielding",
			"#% increased Attack Damage while Dual Wielding",
			"#% increased Attack Damage while holding a Shield",
			"#% increased Attack Speed",
			"#% increased Attack Speed while Dual Wielding",
			"#% increased Attack Speed while holding a Shield",
			"#% increased Attack Speed with Axes",
			"#% increased Attack Speed with Bows",
			"#% increased Attack Speed with Claws",
			"#% increased Attack Speed with Daggers",
			"#% increased Attack Speed with Maces or Sceptres",
			"#% increased Attack Speed with One Handed Melee Weapons",
			"#% increased Attack Speed with Staves",
			"#% increased Attack Speed with Swords",
			"#% increased Attack Speed with Two Handed Melee Weapons",
			"#% increased Attack Speed with Wands",
			"#% increased Attack and Cast Speed",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed while Dual Wielding",
			"#% increased Cast Speed while holding a Shield",
			"#% increased Cast Speed while wielding a Staff",
			"#% increased Cast Speed with Cold Skills",
			"#% increased Cast Speed with Fire Skills",
			"#% increased Cast Speed with Lightning Skills",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Critical Strike Chance with Cold Skills",
			"#% increased Critical Strike Chance with Elemental Skills",
			"#% increased Critical Strike Chance with Fire Skills",
			"#% increased Critical Strike Chance with Lightning Skills",
			"#% increased Critical Strike Chance with One Handed Melee Weapons",
			"#% increased Critical Strike Chance with Two Handed Melee Weapons",
			"#% increased Damage",
			"#% increased Damage over Time",
			"#% increased Damage with Axes",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Bows",
			"#% increased Damage with Claws",
			"#% increased Damage with Daggers",
			"#% increased Damage with Maces or Sceptres",
			"#% increased Damage with One Handed Weapons",
			"#% increased Damage with Poison",
			"#% increased Damage with Staves",
			"#% increased Damage with Swords",
			"#% increased Damage with Two Handed Weapons",
			"#% increased Damage with Wands",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Melee Critical Strike Chance",
			"#% increased Melee Damage",
			"#% increased Mine Damage",
			"#% increased Minion Accuracy Rating",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Spell Damage while Dual Wielding",
			"#% increased Spell Damage while holding a Shield",
			"#% increased Spell Damage while wielding a Staff",
			"#% increased Totem Damage",
			"#% increased Totem Life",
			"#% increased Trap Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Critical Strike Multiplier for Spells",
			"#% to Critical Strike Multiplier while Dual Wielding",
			"#% to Critical Strike Multiplier with Cold Skills",
			"#% to Critical Strike Multiplier with Elemental Skills",
			"#% to Critical Strike Multiplier with Fire Skills",
			"#% to Critical Strike Multiplier with Lightning Skills",
			"#% to Critical Strike Multiplier with One Handed Melee Weapons",
			"#% to Critical Strike Multiplier with Two Handed Melee Weapons",
			"#% to Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"#% to Melee Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Damaging Ailments deal damage #% faster",
			"Minions deal #% increased Damage"
		],
	},
	"Belt": {
		"scourge_implicit": [
			"# to Strength",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased maximum Life"
		],
		"synth_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"#% increased Attack and Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage",
			"#% increased Damage with Ailments",
			"#% increased Damage with Vaal Skills",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Spell Damage per Power Charge",
			"#% increased Strength",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"Damage with Weapons Penetrates #% Cold Resistance",
			"Damage with Weapons Penetrates #% Fire Resistance",
			"Damage with Weapons Penetrates #% Lightning Resistance"
		],
		"corrupt_implicit": [
			"# to Strength",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"#% increased Attack Speed during any Flask Effect",
			"#% increased Cast Speed during any Flask Effect",
			"#% increased Critical Strike Chance during any Flask Effect",
			"#% increased Dexterity",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Strength",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% to Critical Strike Multiplier during any Flask Effect",
			"Anger has #% increased Aura Effect",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Grace has #% increased Aura Effect",
			"Hatred has #% increased Aura Effect",
			"Malevolence has #% increased Aura Effect",
			"Pride has #% increased Aura Effect",
			"Wrath has #% increased Aura Effect",
			"Zealotry has #% increased Aura Effect"
		],
		"implicit": [
			"# to Strength",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"#% increased Global Physical Damage"
		],
		"explicit": [
			"# to # added Fire Damage against Burning Enemies",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed during any Flask Effect",
			"#% increased Attributes",
			"#% increased Cast Speed during any Flask Effect",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance against Shocked Enemies",
			"#% increased Damage",
			"#% increased Damage with Hits against Chilled Enemies",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Energy Shield from Body Armour",
			"#% increased Fire Damage",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Melee Damage during any Flask Effect",
			"#% increased Projectile Attack Damage during any Flask Effect",
			"#% increased Spell Damage during any Flask Effect",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"Damage Penetrates #% Elemental Resistances during any Flask Effect",
			"Overwhelm #% Physical Damage Reduction"
		],
	},
	"Body Armour": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Life",
			"#% increased effect of Non-Curse Auras from your Skills",
			"#% increased maximum Life",
			"#% increased maximum Mana"
		],
		"synth_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Damage",
			"#% increased Attack and Cast Speed",
			"#% increased Attributes",
			"#% increased Spell Damage",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% to Spell Critical Strike Chance",
			"Attacks have #% to Critical Strike Chance",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Gain #% of Maximum Life as Extra Maximum Energy Shield",
			"Grace has #% increased Aura Effect",
			"Minions deal #% increased Damage"
		],
		"corrupt_implicit": [
			"# to Level of all Vaal Skill Gems",
			"# to maximum Mana",
			"#% increased Damage",
			"#% increased Spell Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life"
		],
		"implicit": [
			"# to Level of all Vaal Skill Gems",
			"# to maximum Mana",
			"#% increased Spell Damage"
		],
		"explicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attributes",
			"#% increased Damage per Power Charge",
			"#% increased Dexterity",
			"#% increased Intelligence",
			"#% increased Strength",
			"#% increased effect of Non-Curse Auras from your Skills",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% to Spell Critical Strike Chance",
			"Attacks have #% to Critical Strike Chance",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Maximum Life as Extra Maximum Energy Shield"
		],
	},
	"Boots": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Life",
			"#% increased Totem Life"
		],
		"synth_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Endurance Charges",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Burning Damage",
			"#% increased Damage with Vaal Skills",
			"#% increased Dexterity",
			"#% increased Intelligence",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"Minions deal #% increased Damage"
		],
		"corrupt_implicit": [
			"# to Maximum Endurance Charges",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life"
		],
		"implicit": [
			""
		],
		"explicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Level of all Raise Spectre Gems",
			"# to Maximum Endurance Charges",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Strength",
			"#% increased Totem Damage",
			"Bleeding you inflict deals Damage #% faster",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage",
			"Ignites you inflict deal Damage #% faster",
			"Poisons you inflict deal Damage #% faster"
		],
	},
	"Caster Weapon": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Level of all Chaos Spell Skill Gems",
			"# to Level of all Cold Spell Skill Gems",
			"# to Level of all Fire Spell Skill Gems",
			"# to Level of all Lightning Spell Skill Gems",
			"# to Level of all Physical Spell Skill Gems",
			"# to Level of all Spell Skill Gems",
			"# to Strength",
			"#% chance to deal Triple Damage",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Adds # to # Physical Damage to Spells",
			"Bleeding you inflict deals Damage #% faster",
			"Culling Strike",
			"Damage Penetrates #% Chaos Resistance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Ignites you inflict deal Damage #% faster",
			"Poisons you inflict deal Damage #% faster"
		],
		"synth_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Endurance Charges",
			"# to Maximum Frenzy Charges",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Mana",
			"#% chance to deal Double Damage",
			"#% increased Attack Damage",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Damage",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Damage with Vaal Skills",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% increased maximum Energy Shield",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Bleeding you inflict deals Damage #% faster",
			"Damage Penetrates #% Elemental Resistances",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage",
			"Ignites you inflict deal Damage #% faster",
			"Minions deal #% increased Damage",
			"Poisons you inflict deal Damage #% faster",
			"Spells have a #% chance to deal Double Damage",
			"Triggered Spells deal #% increased Spell Damage"
		],
		"corrupt_implicit": [
			"# to Maximum Power Charges and Maximum Endurance Charges",
			"# to Strength and Dexterity",
			"# to maximum Energy Shield",
			"#% chance to deal Double Damage",
			"#% increased Area Damage",
			"#% increased Cast Speed",
			"#% increased Damage over Time",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Physical Damage (Local)",
			"Damage Penetrates #% Elemental Resistances"
		],
		"implicit": [
			"# to Maximum Power Charges and Maximum Endurance Charges",
			"# to Strength and Dexterity",
			"# to maximum Energy Shield",
			"#% chance to deal Double Damage",
			"#% increased Area Damage",
			"#% increased Cast Speed",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Fire Damage (Local)",
			"Damage Penetrates #% Elemental Resistances"
		],
		"explicit": [
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Level of all Chaos Spell Skill Gems",
			"# to Level of all Cold Spell Skill Gems",
			"# to Level of all Fire Spell Skill Gems",
			"# to Level of all Lightning Spell Skill Gems",
			"# to Level of all Minion Skill Gems",
			"# to Level of all Physical Spell Skill Gems",
			"# to Level of all Spell Skill Gems",
			"# to Maximum Endurance Charges",
			"# to Maximum Frenzy Charges",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Mana",
			"#% Critical Strike Multiplier while a Rare or Unique Enemy is Nearby",
			"#% chance to deal Double Damage",
			"#% increased Accuracy Rating per Frenzy Charge",
			"#% increased Area Damage",
			"#% increased Attack Speed while a Rare or Unique Enemy is Nearby",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed if you've Killed Recently",
			"#% increased Chaos Damage",
			"#% increased Chaos Damage over Time",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance against Blinded Enemies",
			"#% increased Critical Strike Chance against Poisoned Enemies",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Critical Strike Chance if you have Killed Recently",
			"#% increased Critical Strike Chance if you haven't dealt a Critical Strike Recently",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage while Leeching",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Mine Damage",
			"#% increased Physical Damage over Time",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Trap Damage",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Critical Strike Multiplier if you haven't dealt a Critical Strike Recently",
			"#% to Critical Strike Multiplier if you've Killed Recently",
			"#% to Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Chaos Damage to Spells",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Adds # to # Physical Damage to Spells",
			"Anger has #% increased Aura Effect",
			"Auras from your Skills grant #% increased Damage to you and Allies",
			"Bleeding you inflict deals Damage #% faster",
			"Culling Strike",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Elemental Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Non-Chaos Damage as extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Damage of a random Element",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage",
			"Hatred has #% increased Aura Effect",
			"Ignites you inflict deal Damage #% faster",
			"Malevolence has #% increased Aura Effect",
			"Minions deal #% increased Damage",
			"Minions have # to Accuracy Rating",
			"Minions have #% chance to deal Double Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed",
			"Overwhelm #% Physical Damage Reduction",
			"Poisons you inflict deal Damage #% faster",
			"Spells have a #% chance to deal Double Damage",
			"Wrath has #% increased Aura Effect",
			"Zealotry has #% increased Aura Effect"
		],
	},
	"Gloves": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Life",
			"#% increased Attack Speed",
			"#% increased Duration of Ailments on Enemies",
			"#% increased Global Accuracy Rating",
			"#% increased Projectile Damage",
			"Minions deal #% increased Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed"
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Frenzy Charges",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage during any Flask Effect",
			"#% increased Damage over Time",
			"#% increased Damage while Leeching",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Damage with Vaal Skills",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Strength",
			"#% increased Vaal Skill Critical Strike Chance",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"Minions deal #% increased Damage"
		],
		"corrupt_implicit": [
			"# to Maximum Frenzy Charges",
			"#% increased Attack Speed",
			"#% increased Cast Speed",
			"#% increased Damage over Time",
			"#% increased Melee Damage",
			"#% increased Projectile Attack Damage",
			"#% increased Spell Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% to Spell Critical Strike Chance",
			"Attacks have #% to Critical Strike Chance",
			"Exerted Attacks deal #% increased Damage"
		],
		"implicit": [
			"#% increased Damage over Time",
			"#% increased Melee Damage",
			"#% increased Projectile Attack Damage",
			"#% increased Spell Damage",
			"#% increased maximum Mana",
			"Exerted Attacks deal #% increased Damage"
		],
		"explicit": [
			"# to # added Fire Damage against Burning Enemies",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Maximum Frenzy Charges",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Cast Speed",
			"#% increased Critical Strike Chance against Shocked Enemies",
			"#% increased Damage during any Flask Effect",
			"#% increased Damage over Time",
			"#% increased Damage while Leeching",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Hits against Chilled Enemies",
			"#% increased Damage with Poison",
			"#% increased Dexterity",
			"#% increased Duration of Ailments on Enemies",
			"#% increased Effect of Non-Curse Auras from your Skills on Enemies",
			"#% increased Elemental Damage if you've dealt a Critical Strike Recently",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Melee Damage",
			"#% increased Projectile Attack Damage",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Trap Damage",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Cold Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Fire Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Lightning Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Physical Damage for each Impale on Enemy",
			"Adds # to # Physical Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Physical Damage to Attacks",
			"Bleeding you inflict deals Damage #% faster",
			"Culling Strike",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Ignites you inflict deal Damage #% faster",
			"Minions deal #% increased Damage",
			"Poisons you inflict deal Damage #% faster"
		],
	},
	"Helmet": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to maximum Life",
			"#% increased maximum Mana",
			"Nearby Enemies have #% to Chaos Resistance",
			"Nearby Enemies have #% to Cold Resistance",
			"Nearby Enemies have #% to Fire Resistance",
			"Nearby Enemies have #% to Lightning Resistance",
			"Nearby Enemies take #% increased Physical Damage"
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Lightning Damage",
			"#% increased Strength",
			"#% increased effect of Non-Curse Auras from your Skills",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"Gain #% of Physical Damage as Extra Lightning Damage",
			"Ignites you inflict deal Damage #% faster",
			"Minions deal #% increased Damage",
			"Triggered Spells deal #% increased Spell Damage"
		],
		"corrupt_implicit": [
			"# to Maximum Power Charges",
			"#% increased Burning Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"Adds # to # Cold Damage",
			"Damage Penetrates #% Cold Resistance",
			"Minions deal #% increased Damage"
		],
		"implicit": [
			"Adds # to # Cold Damage",
			"Damage Penetrates #% Cold Resistance",
			"Minions deal #% increased Damage"
		],
		"explicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Area Damage",
			"#% increased Burning Damage",
			"#% increased Elemental Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Intelligence",
			"#% increased Mine Damage",
			"#% increased Minion Accuracy Rating",
			"#% increased maximum Mana",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage to Spells",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage to Spells",
			"Ignites you inflict deal Damage #% faster",
			"Minions deal #% increased Damage",
			"Nearby Enemies have #% to Chaos Resistance",
			"Nearby Enemies have #% to Cold Resistance",
			"Nearby Enemies have #% to Fire Resistance",
			"Nearby Enemies have #% to Lightning Resistance",
			"Nearby Enemies take #% increased Elemental Damage",
			"Nearby Enemies take #% increased Physical Damage"
		],
	},
	"Quiver": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to maximum Life",
			"#% increased Attack Speed",
			"#% increased Critical Strike Chance with Bows",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Global Accuracy Rating",
			"#% to Critical Strike Multiplier with Bows"
		],
		"synth_implicit": [
			"# to # Added Cold Damage per Frenzy Charge",
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage while Leeching Life",
			"#% increased Damage while Leeching Mana",
			"#% increased Damage with Poison",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Strength",
			"#% increased Vaal Skill Critical Strike Chance",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% to Global Critical Strike Multiplier",
			"Gain #% of Physical Damage as Extra Damage of a random Element",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Grace has #% increased Aura Effect"
		],
		"corrupt_implicit": [
			"# to # Added Chaos Damage with Bow Attacks",
			"# to # Added Cold Damage with Bow Attacks",
			"# to # Added Fire Damage with Bow Attacks",
			"# to # Added Lightning Damage with Bow Attacks",
			"# to # Added Physical Damage with Bow Attacks",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage"
		],
		"implicit": [
			"# to # Added Fire Damage with Bow Attacks",
			"# to # Added Physical Damage with Bow Attacks",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance"
		],
		"explicit": [
			"# to # Added Cold Damage per Frenzy Charge",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Critical Strike Chance with Bows",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Elemental Damage if you've dealt a Critical Strike Recently",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% to Chaos Damage over Time Multiplier with Attack Skills",
			"#% to Critical Strike Multiplier with Bows",
			"#% to Damage over Time Multiplier with Attack Skills",
			"#% to Fire Damage over Time Multiplier with Attack Skills",
			"#% to Global Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier with Attack Skills",
			"Adds # to # Chaos Damage if you've dealt a Critical Strike Recently",
			"Adds # to # Chaos Damage to Attacks",
			"Adds # to # Cold Damage",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Fire Damage",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Lightning Damage",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Physical Damage to Attacks",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage"
		],
	},
	"Ring": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Endurance Charges",
			"# to Maximum Frenzy Charges",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Elemental Damage with Attack Skills"
		],
		"synth_implicit": [
			"# to # Added Cold Damage per Frenzy Charge",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Endurance Charges",
			"# to Maximum Frenzy Charges",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to all Attributes",
			"#% increased Attack Speed",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Damage",
			"#% increased Damage while Leeching Life",
			"#% increased Damage while Leeching Mana",
			"#% increased Damage with Ailments",
			"#% increased Damage with Poison",
			"#% increased Damage with Vaal Skills",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Spell Damage per Power Charge",
			"#% increased Strength",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage",
			"Adds # to # Cold Damage",
			"Adds # to # Fire Damage",
			"Adds # to # Lightning Damage",
			"Bleeding you inflict deals Damage #% faster",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Grace has #% increased Aura Effect",
			"Ignites you inflict deal Damage #% faster",
			"Poisons you inflict deal Damage #% faster"
		],
		"corrupt_implicit": [
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Strength",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"Adds # to # Cold Damage to Spells and Attacks",
			"Adds # to # Fire Damage to Spells and Attacks",
			"Adds # to # Lightning Damage to Spells and Attacks",
			"Adds # to # Physical Damage to Attacks",
			"Anger has #% increased Aura Effect",
			"Determination has #% increased Aura Effect",
			"Discipline has #% increased Aura Effect",
			"Grace has #% increased Aura Effect",
			"Hatred has #% increased Aura Effect",
			"Malevolence has #% increased Aura Effect",
			"Pride has #% increased Aura Effect",
			"Wrath has #% increased Aura Effect",
			"Zealotry has #% increased Aura Effect"
		],
		"implicit": [
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Chaos Damage",
			"#% increased Elemental Damage",
			"#% increased Global Critical Strike Chance",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"Adds # to # Physical Damage to Attacks"
		],
		"explicit": [
			"# to # Added Cold Damage per Frenzy Charge",
			"# to # Cold Damage per Frenzy Charge",
			"# to # Fire Damage per Endurance Charge",
			"# to # Fire Damage per Endurance Charge",
			"# to # Lightning Damage per Power Charge",
			"# to # Lightning Damage per Power Charge",
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to all Attributes",
			"# to maximum Energy Shield",
			"# to maximum Life",
			"# to maximum Mana",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed per Endurance Charge",
			"#% increased Attack and Cast Speed per Power Charge",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance per Endurance Charge",
			"#% increased Critical Strike Chance per Frenzy Charge",
			"#% increased Damage",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Damage with Vaal Skills",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Critical Strike Chance",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Melee Damage",
			"#% increased Projectile Attack Damage",
			"#% increased Spell Damage",
			"#% increased Spell Damage per Power Charge",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"#% to Critical Strike Multiplier if you've Shattered an Enemy Recently",
			"#% to Critical Strike Multiplier per Power Charge",
			"#% to Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Cold Damage",
			"Adds # to # Cold Damage against Chilled or Frozen Enemies",
			"Adds # to # Cold Damage to Attacks",
			"Adds # to # Fire Damage",
			"Adds # to # Fire Damage against Ignited Enemies",
			"Adds # to # Fire Damage to Attacks",
			"Adds # to # Lightning Damage",
			"Adds # to # Lightning Damage against Shocked Enemies",
			"Adds # to # Lightning Damage to Attacks",
			"Adds # to # Physical Damage to Attacks",
			"Exerted Attacks deal #% increased Damage",
			"Gain #% of Cold Damage as Extra Chaos Damage per Frenzy Charge",
			"Gain #% of Fire Damage as Extra Chaos Damage per Endurance Charge",
			"Gain #% of Lightning Damage as Extra Chaos Damage per Power Charge",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Minions deal #% increased Damage"
		],
	},
	"Shield": {
		"scourge_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Level of all Spell Skill Gems",
			"# to Strength",
			"# to maximum Life",
			"#% increased Attack Speed"
		],
		"synth_implicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Intelligence",
			"# to Maximum Endurance Charges",
			"# to Maximum Frenzy Charges",
			"# to Maximum Power Charges",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Life",
			"# to maximum Mana",
			"#% chance to deal Double Damage",
			"#% increased Attack Damage",
			"#% increased Attack Speed",
			"#% increased Attack and Cast Speed",
			"#% increased Cast Speed",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Damage per Power Charge",
			"#% increased Dexterity",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Physical Damage",
			"#% increased Intelligence",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% increased Strength",
			"#% increased maximum Life",
			"#% increased maximum Mana",
			"#% reduced Mana Cost of Skills",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage"
		],
		"corrupt_implicit": [
			"# to maximum Life",
			"#% increased Spell Damage",
			"#% increased maximum Energy Shield",
			"#% increased maximum Life"
		],
		"implicit": [
			"# to maximum Life",
			"#% increased Spell Damage"
		],
		"explicit": [
			"# to Accuracy Rating",
			"# to Dexterity",
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Level of all Chaos Spell Skill Gems",
			"# to Level of all Cold Spell Skill Gems",
			"# to Level of all Fire Spell Skill Gems",
			"# to Level of all Lightning Spell Skill Gems",
			"# to Level of all Physical Spell Skill Gems",
			"# to Strength",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Life",
			"# to maximum Mana",
			"#% chance to deal Double Damage",
			"#% increased Attack Speed",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% increased effect of Non-Curse Auras from your Skills",
			"#% increased maximum Life",
			"Adds # to # Cold Damage",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage",
			"Adds # to # Lightning Damage to Spells",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage"
		],
	},
	"Wand (Spellslinger)": {
		"scourge_implicit": [
			"# to Intelligence",
			"# to Level of all Chaos Spell Skill Gems",
			"# to Level of all Cold Spell Skill Gems",
			"# to Level of all Fire Spell Skill Gems",
			"# to Level of all Lightning Spell Skill Gems",
			"# to Level of all Physical Spell Skill Gems",
			"# to Level of all Spell Skill Gems",
			"#% chance to deal Triple Damage",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Adds # to # Physical Damage to Spells",
			"Culling Strike",
			"Damage Penetrates #% Chaos Resistance",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Ignites you inflict deal Damage #% faster"
		],
		"synth_implicit": [
			"# to Dexterity",
			"# to Intelligence",
			"# to Strength",
			"# to all Attributes",
			"# to maximum Mana",
			"#% chance to deal Double Damage",
			"#% increased Attack Damage",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Damage",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Damage with Bleeding",
			"#% increased Damage with Poison",
			"#% increased Damage with Vaal Skills",
			"#% increased Elemental Damage",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Spell Damage",
			"#% increased maximum Energy Shield",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Bleeding you inflict deals Damage #% faster",
			"Damage Penetrates #% Elemental Resistances",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage",
			"Ignites you inflict deal Damage #% faster",
			"Minions deal #% increased Damage",
			"Poisons you inflict deal Damage #% faster",
			"Spells have a #% chance to deal Double Damage",
			"Triggered Spells deal #% increased Spell Damage"
		],
		"corrupt_implicit": [
			"#% increased Cast Speed",
			"#% increased Spell Damage",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Lightning Damage (Local)",
			"Damage Penetrates #% Elemental Resistances"
		],
		"implicit": [
			"#% increased Cast Speed",
			"#% increased Spell Damage"
		],
		"explicit": [
			"# to Dexterity and Intelligence",
			"# to Intelligence",
			"# to Level of all Chaos Spell Skill Gems",
			"# to Level of all Cold Spell Skill Gems",
			"# to Level of all Fire Spell Skill Gems",
			"# to Level of all Lightning Spell Skill Gems",
			"# to Level of all Minion Skill Gems",
			"# to Level of all Physical Spell Skill Gems",
			"# to Level of all Spell Skill Gems",
			"# to Strength and Dexterity",
			"# to Strength and Intelligence",
			"# to maximum Mana",
			"#% Critical Strike Multiplier while a Rare or Unique Enemy is Nearby",
			"#% chance to deal Double Damage",
			"#% increased Area Damage",
			"#% increased Attack Speed while a Rare or Unique Enemy is Nearby",
			"#% increased Burning Damage",
			"#% increased Cast Speed",
			"#% increased Cast Speed if you've Killed Recently",
			"#% increased Chaos Damage",
			"#% increased Cold Damage",
			"#% increased Critical Strike Chance for Spells",
			"#% increased Damage per Endurance Charge",
			"#% increased Damage per Frenzy Charge",
			"#% increased Damage per Power Charge",
			"#% increased Elemental Damage with Attack Skills",
			"#% increased Fire Damage",
			"#% increased Global Accuracy Rating",
			"#% increased Global Physical Damage",
			"#% increased Lightning Damage",
			"#% increased Mine Damage",
			"#% increased Projectile Damage",
			"#% increased Spell Damage",
			"#% increased Trap Damage",
			"#% to Chaos Damage over Time Multiplier",
			"#% to Cold Damage over Time Multiplier",
			"#% to Damage over Time Multiplier",
			"#% to Fire Damage over Time Multiplier",
			"#% to Global Critical Strike Multiplier",
			"#% to Physical Damage over Time Multiplier",
			"Adds # to # Chaos Damage (Local)",
			"Adds # to # Chaos Damage to Spells",
			"Adds # to # Cold Damage (Local)",
			"Adds # to # Cold Damage to Spells",
			"Adds # to # Fire Damage (Local)",
			"Adds # to # Fire Damage to Spells",
			"Adds # to # Lightning Damage (Local)",
			"Adds # to # Lightning Damage to Spells",
			"Adds # to # Physical Damage (Local)",
			"Adds # to # Physical Damage to Spells",
			"Anger has #% increased Aura Effect",
			"Auras from your Skills grant #% increased Damage to you and Allies",
			"Damage Penetrates #% Cold Resistance",
			"Damage Penetrates #% Elemental Resistances",
			"Damage Penetrates #% Fire Resistance",
			"Damage Penetrates #% Lightning Resistance",
			"Gain #% of Cold Damage as Extra Chaos Damage",
			"Gain #% of Elemental Damage as Extra Chaos Damage",
			"Gain #% of Fire Damage as Extra Chaos Damage",
			"Gain #% of Lightning Damage as Extra Chaos Damage",
			"Gain #% of Non-Chaos Damage as extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Chaos Damage",
			"Gain #% of Physical Damage as Extra Cold Damage",
			"Gain #% of Physical Damage as Extra Fire Damage",
			"Gain #% of Physical Damage as Extra Lightning Damage",
			"Hatred has #% increased Aura Effect",
			"Ignites you inflict deal Damage #% faster",
			"Malevolence has #% increased Aura Effect",
			"Minions deal #% increased Damage",
			"Minions have # to Accuracy Rating",
			"Minions have #% chance to deal Double Damage",
			"Minions have #% increased Attack Speed",
			"Minions have #% increased Cast Speed",
			"Overwhelm #% Physical Damage Reduction",
			"Spells have a #% chance to deal Double Damage",
			"Wrath has #% increased Aura Effect",
			"Zealotry has #% increased Aura Effect"
		],
	},
}
