goodmod = [
	"# to # Cold Damage per Frenzy Charge",
	"# to # Fire Damage per Endurance Charge",
	"# to # Lightning Damage per Power Charge",
	"# to # added Fire Damage against Burning Enemies",
	"# to Accuracy Rating",
	"# to Dexterity",
	"# to Dexterity and Intelligence",
	"# to Intelligence",
	"# to Level of all Chaos Skill Gems",
	"# to Level of all Chaos Spell Skill Gems",
	"# to Level of all Cold Skill Gems",
	"# to Level of all Cold Spell Skill Gems",
	"# to Level of all Dexterity Skill Gems",
	"# to Level of all Fire Skill Gems",
	"# to Level of all Fire Spell Skill Gems",
	"# to Level of all Intelligence Skill Gems",
	"# to Level of all Lightning Skill Gems",
	"# to Level of all Lightning Spell Skill Gems",
	"# to Level of all Minion Skill Gems",
	"# to Level of all Physical Skill Gems",
	"# to Level of all Physical Spell Skill Gems",
	"# to Level of all Raise Spectre Gems",
	"# to Level of all Spell Skill Gems",
	"# to Level of all Strength Skill Gems",
	"# to Maximum Endurance Charges",
	"# to Maximum Frenzy Charges",
	"# to Maximum Power Charges",
	"# to Maximum Power Charges and Maximum Endurance Charges",
	"# to Strength",
	"# to Strength and Dexterity",
	"# to Strength and Intelligence",
	"# to all Attributes",
	"# to maximum Energy Shield",
	"# to maximum Life",
	"# to maximum Mana",
	"#% Critical Strike Multiplier while a Rare or Unique Enemy is Nearby",
	"#% chance to deal Double Damage",
	"#% chance to deal Double Damage if you have Stunned an Enemy Recently",
	"#% increased Accuracy Rating if you haven't Killed Recently",
	"#% increased Accuracy Rating per Frenzy Charge",
	"#% increased Accuracy Rating with Axes",
	"#% increased Accuracy Rating with Bows",
	"#% increased Accuracy Rating with Claws",
	"#% increased Accuracy Rating with Daggers",
	"#% increased Accuracy Rating with Maces or Sceptres",
	"#% increased Accuracy Rating with Staves",
	"#% increased Accuracy Rating with Swords",
	"#% increased Accuracy Rating with Wands",
	"#% increased Area Damage",
	"#% increased Attack Critical Strike Chance while Dual Wielding",
	"#% increased Attack Damage",
	"#% increased Attack Damage if your other Ring is a Shaper Item",
	"#% increased Attack Damage while Dual Wielding",
	"#% increased Attack Damage while holding a Shield",
	"#% increased Attack Speed",
	"#% increased Attack Speed during any Flask Effect",
	"#% increased Attack Speed if you've dealt a Critical Strike Recently",
	"#% increased Attack Speed while Dual Wielding",
	"#% increased Attack Speed while a Rare or Unique Enemy is Nearby",
	"#% increased Attack Speed while holding a Shield",
	"#% increased Attack Speed with Axes",
	"#% increased Attack Speed with Bows",
	"#% increased Attack Speed with Claws",
	"#% increased Attack Speed with Daggers",
	"#% increased Attack Speed with Maces or Sceptres",
	"#% increased Attack Speed with One Handed Melee Weapons",
	"#% increased Attack Speed with Staves",
	"#% increased Attack Speed with Swords",
	"#% increased Attack Speed with Two Handed Melee Weapons",
	"#% increased Attack Speed with Wands",
	"#% increased Attack and Cast Speed",
	"#% increased Attack and Cast Speed per Endurance Charge",
	"#% increased Attack and Cast Speed per Power Charge",
	"#% increased Attributes",
	"#% increased Burning Damage",
	"#% increased Cast Speed",
	"#% increased Cast Speed during any Flask Effect",
	"#% increased Cast Speed if you've Killed Recently",
	"#% increased Cast Speed if you've dealt a Critical Strike Recently",
	"#% increased Cast Speed while Dual Wielding",
	"#% increased Cast Speed while holding a Shield",
	"#% increased Cast Speed while wielding a Staff",
	"#% increased Cast Speed with Cold Skills",
	"#% increased Cast Speed with Fire Skills",
	"#% increased Cast Speed with Lightning Skills",
	"#% increased Chaos Damage",
	"#% increased Chaos Damage with Attack Skills",
	"#% increased Chaos Damage with Spell Skills",
	"#% increased Cold Damage",
	"#% increased Cold Damage with Attack Skills",
	"#% increased Cold Damage with Spell Skills",
	"#% increased Critical Strike Chance against Blinded Enemies",
	"#% increased Critical Strike Chance against Poisoned Enemies",
	"#% increased Critical Strike Chance against Shocked Enemies",
	"#% increased Critical Strike Chance during any Flask Effect",
	"#% increased Critical Strike Chance for Spells",
	"#% increased Critical Strike Chance for Spells while Dual Wielding",
	"#% increased Critical Strike Chance for Spells while holding a Shield",
	"#% increased Critical Strike Chance for Spells while wielding a Staff",
	"#% increased Critical Strike Chance if you have Killed Recently",
	"#% increased Critical Strike Chance if you haven't dealt a Critical Strike Recently",
	"#% increased Critical Strike Chance if you've been Shocked Recently",
	"#% increased Critical Strike Chance per Endurance Charge",
	"#% increased Critical Strike Chance per Frenzy Charge",
	"#% increased Critical Strike Chance with Cold Skills",
	"#% increased Critical Strike Chance with Elemental Skills",
	"#% increased Critical Strike Chance with Fire Skills",
	"#% increased Critical Strike Chance with Lightning Skills",
	"#% increased Critical Strike Chance with One Handed Melee Weapons",
	"#% increased Critical Strike Chance with Two Handed Melee Weapons",
	"#% increased Damage",
	"#% increased Damage during any Flask Effect",
	"#% increased Damage if you've Killed Recently",
	"#% increased Damage over Time",
	"#% increased Damage over Time while Dual Wielding",
	"#% increased Damage over Time while holding a Shield",
	"#% increased Damage over Time while wielding a Two Handed Weapon",
	"#% increased Damage per 15 Dexterity",
	"#% increased Damage per 15 Intelligence",
	"#% increased Damage per 15 Strength",
	"#% increased Damage per Endurance Charge",
	"#% increased Damage per Frenzy Charge",
	"#% increased Damage per Power Charge",
	"#% increased Damage while Leeching",
	"#% increased Damage while Leeching Life",
	"#% increased Damage while Leeching Mana",
	"#% increased Damage with Ailments",
	"#% increased Damage with Axes",
	"#% increased Damage with Bleeding",
	"#% increased Damage with Bows",
	"#% increased Damage with Claws",
	"#% increased Damage with Daggers",
	"#% increased Damage with Hits against Chilled Enemies",
	"#% increased Damage with Maces or Sceptres",
	"#% increased Damage with One Handed Weapons",
	"#% increased Damage with Poison",
	"#% increased Damage with Staves",
	"#% increased Damage with Swords",
	"#% increased Damage with Two Handed Weapons",
	"#% increased Damage with Wands",
	"#% increased Dexterity",
	"#% increased Duration of Ailments on Enemies",
	"#% increased Elemental Damage",
	"#% increased Elemental Damage if you've dealt a Critical Strike Recently",
	"#% increased Elemental Damage with Attack Skills",
	"#% increased Energy Shield from Body Armour",
	"#% increased Fire Damage",
	"#% increased Fire Damage with Attack Skills",
	"#% increased Fire Damage with Spell Skills",
	"#% increased Global Accuracy Rating",
	"#% increased Global Critical Strike Chance",
	"#% increased Global Physical Damage",
	"#% increased Intelligence",
	"#% increased Lightning Damage",
	"#% increased Lightning Damage with Attack Skills",
	"#% increased Lightning Damage with Spell Skills",
	"#% increased Melee Critical Strike Chance",
	"#% increased Melee Damage",
	"#% increased Melee Damage during any Flask Effect",
	"#% increased Mine Damage",
	"#% increased Minion Accuracy Rating",
	"#% increased Physical Damage with Attack Skills",
	"#% increased Physical Damage with Axes",
	"#% increased Physical Damage with Bows",
	"#% increased Physical Damage with Claws",
	"#% increased Physical Damage with Daggers",
	"#% increased Physical Damage with Maces or Sceptres",
	"#% increased Physical Damage with Spell Skills",
	"#% increased Physical Damage with Staves",
	"#% increased Physical Damage with Swords",
	"#% increased Physical Damage with Wands",
	"#% increased Projectile Attack Damage",
	"#% increased Projectile Attack Damage during any Flask Effect",
	"#% increased Projectile Damage",
	"#% increased Spell Damage",
	"#% increased Spell Damage during any Flask Effect",
	"#% increased Spell Damage if your other Ring is an Elder Item",
	"#% increased Spell Damage per Power Charge",
	"#% increased Spell Damage while Dual Wielding",
	"#% increased Spell Damage while holding a Shield",
	"#% increased Spell Damage while wielding a Staff",
	"#% increased Strength",
	"#% increased Totem Damage",
	"#% increased Trap Damage",
	"#% increased Vaal Skill Critical Strike Chance",
	"#% increased effect of Non-Curse Auras from your Skills",
	"#% increased maximum Energy Shield",
	"#% increased maximum Life",
	"#% increased maximum Mana",
	"#% reduced Mana Cost of Skills",
	"#% to Chaos Damage over Time Multiplier",
	"#% to Cold Damage over Time Multiplier",
	"#% to Critical Strike Multiplier during any Flask Effect",
	"#% to Critical Strike Multiplier for Spells",
	"#% to Critical Strike Multiplier for Spells while Dual Wielding",
	"#% to Critical Strike Multiplier for Spells while holding a Shield",
	"#% to Critical Strike Multiplier for Spells while wielding a Staff",
	"#% to Critical Strike Multiplier if you haven't dealt a Critical Strike Recently",
	"#% to Critical Strike Multiplier if you've Killed Recently",
	"#% to Critical Strike Multiplier if you've Shattered an Enemy Recently",
	"#% to Critical Strike Multiplier per Power Charge",
	"#% to Critical Strike Multiplier while Dual Wielding",
	"#% to Critical Strike Multiplier with Axes",
	"#% to Critical Strike Multiplier with Bows",
	"#% to Critical Strike Multiplier with Claws",
	"#% to Critical Strike Multiplier with Cold Skills",
	"#% to Critical Strike Multiplier with Daggers",
	"#% to Critical Strike Multiplier with Elemental Skills",
	"#% to Critical Strike Multiplier with Fire Skills",
	"#% to Critical Strike Multiplier with Lightning Skills",
	"#% to Critical Strike Multiplier with Maces or Sceptres",
	"#% to Critical Strike Multiplier with One Handed Melee Weapons",
	"#% to Critical Strike Multiplier with Staves",
	"#% to Critical Strike Multiplier with Swords",
	"#% to Critical Strike Multiplier with Two Handed Melee Weapons",
	"#% to Critical Strike Multiplier with Wands",
	"#% to Damage over Time Multiplier",
	"#% to Fire Damage over Time Multiplier",
	"#% to Global Critical Strike Multiplier",
	"#% to Melee Critical Strike Multiplier",
	"#% to Physical Damage over Time Multiplier",
	"#% to Spell Critical Strike Chance",
	"Adds # to # Chaos Damage",
	"Adds # to # Chaos Damage (Local)",
	"Adds # to # Chaos Damage if you've dealt a Critical Strike Recently",
	"Adds # to # Chaos Damage to Attacks",
	"Adds # to # Chaos Damage to Spells",
	"Adds # to # Chaos Damage to Spells while Dual Wielding",
	"Adds # to # Chaos Damage to Spells while holding a Shield",
	"Adds # to # Chaos Damage to Spells while wielding a Two Handed Weapon",
	"Adds # to # Cold Damage",
	"Adds # to # Cold Damage (Local)",
	"Adds # to # Cold Damage against Chilled or Frozen Enemies",
	"Adds # to # Cold Damage if you've dealt a Critical Strike Recently",
	"Adds # to # Cold Damage to Attacks",
	"Adds # to # Cold Damage to Axe Attacks",
	"Adds # to # Cold Damage to Bow Attacks",
	"Adds # to # Cold Damage to Claw Attacks",
	"Adds # to # Cold Damage to Dagger Attacks",
	"Adds # to # Cold Damage to Mace or Sceptre Attacks",
	"Adds # to # Cold Damage to Spells",
	"Adds # to # Cold Damage to Spells and Attacks",
	"Adds # to # Cold Damage to Spells while Dual Wielding",
	"Adds # to # Cold Damage to Spells while holding a Shield",
	"Adds # to # Cold Damage to Spells while wielding a Two Handed Weapon",
	"Adds # to # Cold Damage to Staff Attacks",
	"Adds # to # Cold Damage to Sword Attacks",
	"Adds # to # Cold Damage to Wand Attacks",
	"Adds # to # Fire Damage",
	"Adds # to # Fire Damage (Local)",
	"Adds # to # Fire Damage against Ignited Enemies",
	"Adds # to # Fire Damage if you've dealt a Critical Strike Recently",
	"Adds # to # Fire Damage to Attacks",
	"Adds # to # Fire Damage to Axe Attacks",
	"Adds # to # Fire Damage to Bow Attacks",
	"Adds # to # Fire Damage to Claw Attacks",
	"Adds # to # Fire Damage to Dagger Attacks",
	"Adds # to # Fire Damage to Mace or Sceptre Attacks",
	"Adds # to # Fire Damage to Spells",
	"Adds # to # Fire Damage to Spells and Attacks",
	"Adds # to # Fire Damage to Spells while Dual Wielding",
	"Adds # to # Fire Damage to Spells while holding a Shield",
	"Adds # to # Fire Damage to Spells while wielding a Two Handed Weapon",
	"Adds # to # Fire Damage to Staff Attacks",
	"Adds # to # Fire Damage to Sword Attacks",
	"Adds # to # Fire Damage to Wand Attacks",
	"Adds # to # Lightning Damage",
	"Adds # to # Lightning Damage (Local)",
	"Adds # to # Lightning Damage against Shocked Enemies",
	"Adds # to # Lightning Damage if you've dealt a Critical Strike Recently",
	"Adds # to # Lightning Damage to Attacks",
	"Adds # to # Lightning Damage to Axe Attacks",
	"Adds # to # Lightning Damage to Bow Attacks",
	"Adds # to # Lightning Damage to Claw Attacks",
	"Adds # to # Lightning Damage to Dagger Attacks",
	"Adds # to # Lightning Damage to Mace or Sceptre Attacks",
	"Adds # to # Lightning Damage to Spells",
	"Adds # to # Lightning Damage to Spells and Attacks",
	"Adds # to # Lightning Damage to Spells while Dual Wielding",
	"Adds # to # Lightning Damage to Spells while holding a Shield",
	"Adds # to # Lightning Damage to Spells while wielding a Two Handed Weapon",
	"Adds # to # Lightning Damage to Staff Attacks",
	"Adds # to # Lightning Damage to Sword Attacks",
	"Adds # to # Lightning Damage to Wand Attacks",
	"Adds # to # Physical Damage (Local)",
	"Adds # to # Physical Damage for each Impale on Enemy",
	"Adds # to # Physical Damage if you've dealt a Critical Strike Recently",
	"Adds # to # Physical Damage to Attacks",
	"Adds # to # Physical Damage to Axe Attacks",
	"Adds # to # Physical Damage to Bow Attacks",
	"Adds # to # Physical Damage to Claw Attacks",
	"Adds # to # Physical Damage to Dagger Attacks",
	"Adds # to # Physical Damage to Mace or Sceptre Attacks",
	"Adds # to # Physical Damage to Spells",
	"Adds # to # Physical Damage to Spells while Dual Wielding",
	"Adds # to # Physical Damage to Spells while holding a Shield",
	"Adds # to # Physical Damage to Spells while wielding a Two Handed Weapon",
	"Adds # to # Physical Damage to Staff Attacks",
	"Adds # to # Physical Damage to Sword Attacks",
	"Adds # to # Physical Damage to Wand Attacks",
	"Anger has #% increased Aura Effect",
	"Attacks have #% to Critical Strike Chance",
	"Auras from your Skills grant #% increased Damage to you and Allies",
	"Bleeding you inflict deals Damage #% faster",
	"Damage Penetrates #% Cold Resistance",
	"Damage Penetrates #% Elemental Resistance if you haven't Killed Recently",
	"Damage Penetrates #% Elemental Resistances",
	"Damage Penetrates #% Elemental Resistances during any Flask Effect",
	"Damage Penetrates #% Fire Resistance",
	"Damage Penetrates #% Lightning Resistance",
	"Damage with Weapons Penetrates #% Cold Resistance",
	"Damage with Weapons Penetrates #% Fire Resistance",
	"Damage with Weapons Penetrates #% Lightning Resistance",
	"Determination has #% increased Aura Effect",
	"Discipline has #% increased Aura Effect",
	"Exerted Attacks deal #% increased Damage",
	"Gain #% of Cold Damage as Extra Chaos Damage",
	"Gain #% of Cold Damage as Extra Chaos Damage per Frenzy Charge",
	"Gain #% of Elemental Damage as Extra Chaos Damage",
	"Gain #% of Fire Damage as Extra Chaos Damage",
	"Gain #% of Fire Damage as Extra Chaos Damage per Endurance Charge",
	"Gain #% of Lightning Damage as Extra Chaos Damage",
	"Gain #% of Lightning Damage as Extra Chaos Damage per Power Charge",
	"Gain #% of Maximum Life as Extra Maximum Energy Shield",
	"Gain #% of Non-Chaos Damage as extra Chaos Damage",
	"Gain #% of Physical Damage as Extra Chaos Damage",
	"Gain #% of Physical Damage as Extra Cold Damage",
	"Gain #% of Physical Damage as Extra Damage of a random Element",
	"Gain #% of Physical Damage as Extra Fire Damage",
	"Gain #% of Physical Damage as Extra Fire Damage if you've dealt a Critical Strike Recently",
	"Gain #% of Physical Damage as Extra Lightning Damage",
	"Grace has #% increased Aura Effect",
	"Hatred has #% increased Aura Effect",
	"Ignites you inflict deal Damage #% faster",
	"Malevolence has #% increased Aura Effect",
	"Minions deal # to # Added Lightning Damage",
	"Minions deal # to # additional Chaos Damage",
	"Minions deal # to # additional Cold Damage",
	"Minions deal # to # additional Fire Damage",
	"Minions deal # to # additional Physical Damage",
	"Minions deal #% increased Damage",
	"Minions deal #% increased Damage if you've used a Minion Skill Recently",
	"Minions have # to Accuracy Rating",
	"Minions have #% chance to deal Double Damage",
	"Minions have #% increased Attack Speed",
	"Minions have #% increased Attack and Cast Speed if you or your Minions have Killed Recently",
	"Minions have #% increased Cast Speed",
	"Nearby Enemies have #% to Chaos Resistance",
	"Nearby Enemies have #% to Cold Resistance",
	"Nearby Enemies have #% to Fire Resistance",
	"Nearby Enemies have #% to Lightning Resistance",
	"Nearby Enemies take #% increased Elemental Damage",
	"Nearby Enemies take #% increased Physical Damage",
	"Overwhelm #% Physical Damage Reduction",
	"Poisons you inflict deal Damage #% faster",
	"Pride has #% increased Aura Effect",
	"Spells have a #% chance to deal Double Damage",
	"Triggered Spells deal #% increased Spell Damage",
	"Vaal Skills deal #% increased Damage",
	"Wrath has #% increased Aura Effect",
	"Zealotry has #% increased Aura Effect"
]
